### ISSUE TITLE
Erreur lors de la publication d'un article

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/site#46]
```
[2019-12-19 11:38:10,540] ERROR in app: Exception on /admin/post/edit/actualites/1576681254 [POST]
Traceback (most recent call last):
  File "/home/afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/afpy-org/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/afpy-org/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/afpy-org/src/afpy.py", line 174, in save_post_admin
    files=request.files,
  File "/home/afpy-org/src/data_xml.py", line 144, in save_post
    post_image.save(str(post.parent / filename))
  File "/home/afpy-org/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2800, in save
    dst = open(dst, "wb")
IsADirectoryError: [Errno 21] est un dossier: '/home/afpy-org/src/posts/actualites/waiting/1576681254'
```

**Comment by Mindiell** [comment]
De ce que je vois dans le code le jour de l'erreur, je me demande si c'est pas l'absence de parenthèses qui a provoqué ça : 
- "if ACTION_DELETE_IMAGE in form and image_path.exists:" Ici l'absence de parenthèses à la fin fait passer le if si j'ai bien tout suivi
- Et donc derrière il tente un unlink d'un répertoire et non d'un fichier

Si c'est bien ça, la modification du code par la suite a corrigé ce souci non ?

**Comment by Seluj78** [comment]
On peux close cette issue après que https://github.com/AFPy/site/pull/58 soit mergé normalement 🎉

**Comment by Mindiell** [comment]
On peut close !

**Comment by Mindiell** [comment]
On peut close !
